### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by jbgriffith** [iamkalai/SNStandardsFramework#1]
Images are broken on the readme

**Comment by jbgriffith** [comment]
![screenshot_20170823-064950](https://user-images.githubusercontent.com/1854971/29619252-7e512d18-87cf-11e7-9ff1-5b80caa6d135.png)

**Comment by iamkalai** [comment]
I have tried viewing the readme file on mobile and desktop as well but I don't see this error.

Can you confirm if you are able to replicate this? And which browser are you using?

**Comment by iamkalai** [comment]
I have tried by switching user agent as well and this appears fine. Hence closing the issue.
